name: PR Agent

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  issues: write
  pull-requests: write
  contents: write

jobs:
  pr_agent:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run PR Agent
        uses: qodo-ai/pr-agent@v0.32
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          GITHUB_ACTION_CONFIG.AUTO_DESCRIBE: "true"
          GITHUB_ACTION_CONFIG.AUTO_REVIEW: "false"